--alter session set current_schema = proyectofinal;

CREATE VIEW ListasUsuarios AS
SELECT USERNAME,
       LISTAS.NOMBRE AS Lista,
       ANIMES.NOMBRE AS anime
FROM USUARIOS,
     LISTAS,
     ANIMES,
     LISTA_ANIME
WHERE ID_USUARIO = LI_ID_NORMAL
  AND LISTAS.ID_LISTA = LISTA_ANIME.ID_LISTA
  AND ID_ANIME = LISTA_ANIME.LA_ID_ANIME;

CREATE VIEW UsuariosComunidad AS
SELECT USUARIOS.ID_USUARIO,
       Username,
       ID_ANIME,
       ANIMES.NOMBRE AS Comunidad
FROM USUARIOS,
     NORMAL_COMUNIDAD,
     COMUNIDADES,
     ANIMES
WHERE USUARIOS.ID_USUARIO = NORMAL_COMUNIDAD.ID_USUARIO
  AND COMUNIDADES.ID_COMUNIDAD = NORMAL_COMUNIDAD.ID_COMUNIDAD
  AND ID_ANIME = CO_ID_ANIME;

    CREATE VIEW UsuariosPublicaciones AS
SELECT USERNAME, ANIMES.NOMBRE AS Comunidad, CONTENIDO
FROM USUARIOS,
     ANIMES,
     PUBLICACIONES,
     COMUNIDADES
WHERE ID_COMUNIDAD = PB_ID_COMUNIDAD
  AND ID_ANIME = CO_ID_ANIME
  AND ID_USUARIO = PB_ID_NORMAL
ORDER BY USERNAME;